Feature/expand package
ekut/mediawiki-sdk-php pull request #2
Opened 2022-09-25 12:53 UTC by eljump

[LEARN-POEMS-T-23](https://webconsul.jetbrains.space/p/learn-poems/issues/23)

2022-09-26 10:40 UTC, ekut requested changes
Вот бы с языком wiki-движка разобраться
Потому что запрос будет идти с определённым языком.

2022-09-26 10:40 UTC, ekut commented on .env
> -MEDIAWIKI_API_ROOT="https://en.wikipedia.org/w/rest.php"
Файл `.env` нужно выпилить из репозитория. Я его впопыхах добавил, когда к ролику готовился. Это ошибка, нужно исправить. В репе должен быть только `.env.example`
Я делал отдельное issue на эту тему, но раз ты уже тронул этот файл, то лучше сразу и выпилить.

2022-09-26 10:40 UTC, ekut commented on .env.example
> +MEDIAWIKI_HOST="https://www.wikipedia.org/"
не пойдёт, потому что в итоге нам нужно будет конструировать запросы с языком. То есть:
`https://{lang}.{MEDIAWIKI_HOST}/...`
Понимаешь? Поэтому я и хотел не URL здесь хранить, а именно хост

2022-09-26 10:40 UTC, ekut commented on README.md
> +MEDIAWIKI_HOST="https://www.wikipedia.org/"
Ну, и соответственно то же самое.

2022-09-26 10:40 UTC, ekut commented on src/MediaWikiAdapter.php
> +            $_ENV['MEDIAWIKI_HOST'];
Вот здесь у нас как раз должен использоваться параметр {lang}, который мы сюда каким-то образом передали.

2022-09-26 10:44 UTC, ekut requested changes

2022-09-26 10:44 UTC, ekut commented on src/MediaWikiAdapter.php
>                      'User-Agent'   => 'ekut WikiMedia SDK (PHP)/1.0',
давай здесь `ekut` заменим на WebConsul уже?

2022-09-26 14:23 UTC, eljump commented on .env.example
> +MEDIAWIKI_HOST="https://www.wikipedia.org/"
Я взял строку из задачи)
Получается нужно хранить только  "wikipedia.org/",
а что делать с commons?
+ я насколько понял, под языки у нас будет отдельный таск, я предположил что в нём и будем это реализовывать, а на данный момент такой задачи не стояло, поэтому хост я указал целиком

2022-09-26 17:41 UTC, eljump commented on .env
> -MEDIAWIKI_API_ROOT="https://en.wikipedia.org/w/rest.php"
сделал

2022-09-26 17:42 UTC, eljump commented on src/MediaWikiAdapter.php
>                      'User-Agent'   => 'ekut WikiMedia SDK (PHP)/1.0',
сделал

2022-09-27 08:56 UTC, ekut approved these changes
Поехали! :)

2022-09-27 08:57 UTC, merged